### ISSUE TITLE
my app crashes while generating pdf

### ISSUE THREAD

**Issue by ramsuthar305** [DavBfr/dart_pdf#130]
**Describe the bug**
I am trying to place picture in my pdf but as soon as i run generate pdf function which generates pdf the app crashes. As soon as I remove `printing: ^2.1.3` from my pubspec.yaml it works fine. I am stuck please help me .

This is my code 

```
import 'package:flutter/material.dart';
import 'items.dart';
import 'package:flutter/services.dart';
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';
import 'package:pdf/widgets.dart' as pdfLib;
import 'package:path_provider/path_provider.dart';

_generatePdfAndView(context) async {
    
    final pdfLib.Document pdf = pdfLib.Document(deflate: zlib.encode);
    const imageProvider = const AssetImage('assets/id.jpg');
    final PdfImage sklogo = await pdfImageFromImageProvider(pdf: pdf.document, image: imageProvider);

    final PdfColor c1 = PdfColor.fromInt(4294278144);
    pdf.addPage(
      pdfLib.MultiPage(
        margin: pdfLib.EdgeInsets.symmetric(vertical: 15.0),
        footer: (context) {
          return pdfLib.Container(
              child: pdfLib.Center(child: pdfLib.Text('this is footer')));
        },
        build: (context) => [
          pdfLib.Header(
              child: pdfLib.Stack(children: <pdfLib.Widget>[
            pdfLib.Align(
              alignment: pdfLib.Alignment.center,
              child: pdfLib.Column(children: <pdfLib.Widget>[
                pdfLib.Center(
                    child: pdfLib.Text('BHAVRARAM .K. SUTHAR',
                        style: pdfLib.TextStyle(
                          color: c1,
                          fontWeight: pdfLib.FontWeight.bold,
                          fontSize: 16.0,
                        ))),
                pdfLib.Center(
                    child: pdfLib.Text('ALL TYPES OF TEAK FURNITURE CONTRACTOR',
                        style: pdfLib.TextStyle(
                          fontWeight: pdfLib.FontWeight.bold,
                          fontSize: 10.0,
                        ))),
              ]),
            ),
            pdfLib.Positioned(
                left: 500.0,
                child: pdfLib.Column(children: <pdfLib.Widget>[
                  pdfLib.Image(sklogo),
                ]))
          ])),
          pdfLib.Container(
            margin: pdfLib.EdgeInsets.symmetric(horizontal: 30.0),
            child: pdfLib.Table.fromTextArray(
              context: context,
              data: sab(),
            ),
          ),
        ],
      ),
    );

    final String dir = (await getExternalStorageDirectory()).path;
    final String path = '$dir/myflutter.pdf';

    final File file = File(path);
    await file.writeAsBytes(pdf.save());
    print('file saveddddddddddddddd at $path');
  }
}
```

**Expected behavior**
I want to insert images in assets.

**Flutter Doctor**

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/ram/Downloads/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/ram/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /snap/android-studio/77/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/77/android-studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • Redmi Note 5 Pro • 47c73d87 • android-arm64 • Android 9 (API 28)

• No issues found!
```
**this is my Buid.gradle**
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.quotation"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

**this is my pubspec.yaml**
```
name: quotation
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^0.1.8
  pdf: ^1.3.17
  printing: ^2.1.3
  path_provider: ^1.2.0
  local_auth:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand.ttf
    - family: Teko
      fonts:
        - asset: fonts/Teko-Light.ttf

    - family: Roboto
      fonts:
          - asset: fonts/Roboto-Regular.ttf

    - family: Book
      fonts:
          - asset: fonts/bookantiqua.ttf
  assets:
    - assets/id.jpg
    

  uses-material-design: true
```
**Desktop**
 - [ ] Android

**Device information**
 - Xiomi Redmi Note 5 pro
 - OS: MIUI 10.3.1 stable based on Android Pie 9.0
