### ISSUE TITLE
Newer releases don't work on web

### ISSUE THREAD

**Issue by adjentz** [DavBfr/dart_pdf#131]
**Describe the bug**
Using any version above 1.3.13 doesn't work when compiled for web (at least with ddc).

**To Reproduce**
Adding any reference to package:pdf will cause `webdev serve` to fail
```dart
import 'package:pdf/widgets.dart';

void main() {
  final pdf = Document();
}

```
With this "warning"
> Skipping compiling pdf_test|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:
 pdf|lib/src/io.dart

because compiling main.dart is skipped, the application fails

**Expected behavior**
`webdev serve` should successfully compile without skipping compiling main.dart

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Android
 - [x] Browser

**Comment by DavBfr** [comment]
Can you test the last sources from GitHub?
Use in your pubspec.yml:

```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf
      path: pdf
```
