### ISSUE TITLE
Importing pdf_crypto doesn't work

### ISSUE THREAD

**Issue by rhowelp** [DavBfr/dart_pdf#1767]
I would like to add a password in the pdf file and so I tried to import pdf_crypto but it doesn't work
```
  pdf_crypto:
    hosted:
      name: pdf_crypto
      url: https://pub.nfet.net/PASSWORD
    version: ^3.3.9
```

```
Resolving dependencies...
Because simone depends on pdf_crypto any which doesn't exist (could not find package pdf_crypto at https://pub.nfet.net/PASSWORD/), version solving failed.
```

I am using Flutter v3.24.3
```
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (7 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```
