### ISSUE TITLE
❌ Error when adding a TTF font from assets to my pdf

### ISSUE THREAD

**Issue by David-Carballo** [DavBfr/dart_pdf#1854]
**Describe the bug**
When I try to load the font "[Mulish](https://fonts.google.com/specimen/Mulish)" from my assets, adding it to my pdf theme, I get the error on pdf.save():

`Exception has occurred.
IndexError (RangeError (byteOffset): Index out of range: index should be less than 106523: 106524)`

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
var theme = pw.ThemeData.withFont(
    base: pw.Font.ttf(await rootBundle.load('lib/assets/fonts/Mulish-Regular.ttf')),
  );
  
  final pdf = pw.Document(
    theme: theme,
  );
```

pubspec.yaml:
```
fonts:
    - family: Mulish
      fonts:
        - asset: lib/assets/fonts/Mulish-Regular.ttf
        - asset: lib/assets/fonts/Mulish-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Mulish-BoldItalic.ttf
          style: italic
          weight: 700
```

**Expected behavior**
Saving the PDF should work without a problem, not throw an error.

**Flutter Doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Versi¢n 10.0.26100.4349], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.101.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

**Desktop (please complete the following information):**
 - [x] Windows 11

**Additional context**
If I load the _Mulish-VariableFont_wght_, it works fine! But I can't use font weight. 
I find this closed [issue-1564](https://github.com/DavBfr/dart_pdf/issues/1546) with the same problem but it does not work for me.
