### ISSUE TITLE
TextStyle is not working

### ISSUE THREAD

**Issue by Azzeccagarbugli** [DavBfr/dart_pdf#322]
**Describe the bug**

The property `pw.FontWeight.bold` is not working 

**To Reproduce**

```dart
 pw.Text(
          "Discover",
          style: pw.TextStyle(
            fontSize: 42,
            color: PdfColors.grey900,
            fontWeight: pw.FontWeight.bold
          ),
        ),
```

**Expected behavior**

Visualising the correct weight for the font selected

**Flutter Doctor**

```
 flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Linux, locale it_IT.UTF-8)
    • Flutter version 1.17.2 at /opt/flutter
    • Framework revision 5f21edf8b6 (10 giorni fa), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/azzeccagarbugli/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Desktop (please complete the following information):**
 - [ ] iOS
 - [ ] Browser
 - [x] Android

**Smartphone (please complete the following information):**
 - Device: [Pixel 2XL]
 - OS: [Android]
 - Version [Android 10]

**Additional context**

I can't really understand what I'm doing wrong.

I followed the proposal guide but is not working. I added correctly the `ThemeData` in the following way: 

 ```dart
theme: pw.ThemeData.withFont(
      base: pw.Font.ttf(
        await rootBundle.load(
          "assets/fonts/Quicksand-Regular.ttf",
        ),
      ),
      bold: pw.Font.ttf(
        await rootBundle.load(
          "assets/fonts/Quicksand-Bold.ttf",
        ),
      ),
    ),
```

And in the `pubspec.yml` I got the following configuration: 

```yml
fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
```

But I always get the same error: 

```
E/flutter (25531): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:pdf/src/font_metrics.dart': Failed assertion: line 39 pos 16: 'top <= bottom': is not true.
E/flutter (25531): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
E/flutter (25531): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
E/flutter (25531): #2      new PdfFontMetrics 
package:pdf/src/font_metrics.dart:39
E/flutter (25531): #3      TtfParser._parseGlyphs 
package:pdf/src/ttf_parser.dart:247
E/flutter (25531): #4      new TtfParser 
package:pdf/src/ttf_parser.dart:56
E/flutter (25531): #5      new PdfTtfFont 
package:pdf/src/ttffont.dart:24
E/flutter (25531): #6      TtfFont.buildFont 
package:pdf/widgets/font.dart:155
E/flutter (25531): #7      Font.getFont 
package:pdf/widgets/font.dart:133
E/flutter (25531): #8      RichText.layout.<anonymous closure> 
```

Thanks in advance!

**Comment by DavBfr** [comment]
The fonts declared like this in your pubspec can be used only by Flutter. Add them to the assets too.

**Comment by Azzeccagarbugli** [comment]
> The fonts declared like this in your pubspec can be used only by Flutter. Add them to the assets too.

I just added them in this way:

```yaml
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Quicksand-Bold.ttf
    - assets/fonts/Quicksand-Regular.ttf
```

But I got the same issue unfortunately
