### ISSUE TITLE
Gradle dependency hell with flutter upgrade - AndroidX

### ISSUE THREAD

**Issue by biancashouse** [DavBfr/dart_pdf#45]
Thanks to Time Machine, I'm able to turn the clock back to before 'flutter upgrade'.
Is there a plan to get pdf and printing packages to work with the latest flutter 1.2.1, which depends on the newer AndroidX ?
Right now I'm using 👍 
  pdf: ^1.3.2
  printing: ^1.3.2

**Comment by DavBfr** [comment]
A patch is committed to Github, you can try it using:
```yaml
dependency_overrides:
  printing:
    git: 
      url: https://github.com/DavBfr/dart_pdf
      path: printing
```

in your `pubspec.yaml`
