### ISSUE TITLE
Using latest PDF & Printing packages

### ISSUE THREAD

**Issue by Cressplant** [DavBfr/dart_pdf#483]
Hi there,

Thank you for the great package!

I'm trying to use the latest version via GitHub but I also rely on the Printing package, and I get this error when running Pub Get while using both.

```
Because every version of printing from path depends on pdf from hosted and test_project depends on pdf from path, printing from path is forbidden.
So, because test_project depends on printing from path, version solving failed.
pub get failed (1; So, because test_project depends on printing from path, version solving failed.)
```

Is there a way of doing getting around this or do I have to wait until its on pub.dev? Do you know when 1.13.0 will go on there yet?

Thanks again!

**Comment by DavBfr** [comment]
What do you use for your pubspec.yaml?

**Comment by Cressplant** [comment]
Thanks for getting back to me so quickly!

Tried adding manually to project:

``  pdf:
    path: packages/dart_pdf-master/pdf

  printing:
    path: packages/dart_pdf-master/printing``

& via GitHub:

``   pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf/

  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: printing/``

& both while importing pub.dev printing package, e.g. :

``  pdf:
    path: packages/dart_pdf-master/pdf

  printing: ^3.7.1``

**Comment by DavBfr** [comment]
you can use it like this:

```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf

  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
    path: printing

```
