### ISSUE TITLE
TextOverflow.clip and softwrap not working

### ISSUE THREAD

**Issue by phaylali** [DavBfr/dart_pdf#708]
I have a string that i need to but clipped exactly at the max width , when I apply textoverflow it just sends the entire word that didn't fit to the next line, I want to have maxlines:1 , and softwrap doesn't do anything

**Comment by DavBfr** [comment]
@phaylali try the master branch, it has a fix for softwrap.

**Comment by phaylali** [comment]
> @phaylali try the master branch, it has a fix for softwrap.

Okay I will try , can you give me the correct way to import the master branch from github (in pubspec.yaml) I did but there is a problem of dependencies because i have the printing package too ,

**Comment by DavBfr** [comment]
```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf
```
