### ISSUE TITLE
HTML to PDF cold start not working on Android

### ISSUE THREAD

**Issue by vikasgupta4190** [DavBfr/dart_pdf#717]
**Describe the bug**
When the application installs the first time, Printing.convertHtml() first showing blank but save and other features working properly. But the second time it's working properly.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
  final values = await Printing.convertHtml(
        format: format.copyWith(
            marginLeft: 0, marginTop: 0, marginRight: 0, marginBottom: 0),
        html: widget.resumeData);

```

**Expected behavior**
I expect every time pdf preview work properly.Can you please help . Thanks.
**Screenshots**
![image](https://user-images.githubusercontent.com/17292049/120889537-4e006f00-c61b-11eb-80c2-146fde76d4ad.png)

**Comment by DavBfr** [comment]
Do you have the same behavior using the master branch?
Add this to your pubspec.yaml:

```yaml
dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: printing
```
