### ISSUE TITLE
Application crashes when I am trying to print [macOS]

### ISSUE THREAD

**Issue by niklasbartsch** [DavBfr/dart_pdf#858]
I tried to print a pdf on my Mac and it crashes the application.
I activated the printing capability in Xcode.

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
Printing.layoutPdf(
      onLayout: (format) async => await generatePdf(format),
);
```

**Expected behavior**
showing the printing dialog

**Screenshots**

![Bildschirmfoto 2021-11-19 um 15 21 36](https://user-images.githubusercontent.com/32355097/142642536-af550cd8-2e27-4973-90b5-4cce26a0b71e.png)

**Console:**
'printing/PrintJob.swift:156: Fatal error: Unexpectedly found nil while unwrapping an Optional value'

 - macOS
 - Device: MacBook Pro
 - OS: 12.0.1

**Additional context**
It works on web.

**Comment by DavBfr** [comment]
@niklasbartsch  Can you test printing with the master branch to validate the fix?

    In your `pubspec.yaml` file, add:

```yaml
    dependency_overrides:
      printing:
        git:
          url: https://github.com/DavBfr/dart_pdf.git
          ref: master
        path: printing
```

**Comment by bluejeans117** [comment]
```
dependency_overrides:
      printing:
        git:
          url: https://github.com/DavBfr/dart_pdf.git
          ref: master
          path: printing

```
These would be the correct lines to add.

Flutter doesn't show any logs when the crash happens, and xcode shows unrelated logs (as far as I can tell). Here's the [xcode debug output](https://batbin.me/bellowsmaking)
