### ISSUE TITLE
assertion 'GTK_IS_PRINTER (printer)' failed

### ISSUE THREAD

**Issue by ttulka** [DavBfr/dart_pdf#877]
**Describe the bug**
This is related to the `printing` module and occurs on Linux only (Ubuntu/Kubuntu/Lubuntu 20.04).
The printing dialog is shown correctly, the printer is displayed together with the `Print to file` option.
However, when the Print button is clicked, exceptions occur:

```
Gtk-CRITICAL **: 11:20:26.462: gtk_printer_accepts_pdf: assertion 'GTK_IS_PRINTER (printer)' failed
GLib-GObject-CRITICAL **: 11:20:26.462: g_object_new_valist: invalid unclassed object pointer for value type 'GtkPrinter'
Gtk-CRITICAL **: 11:20:26.463: gtk_printer_get_backend: assertion 'GTK_IS_PRINTER (printer)' failed
GLib-GObject-CRITICAL **: 11:20:26.463: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
```

**To Reproduce**
Code snippet to reproduce the behavior:
```dart
final pw.Document doc = _buildPdfDocument();
final Uint8List pdf = await doc.save();
Printing.layoutPdf(onLayout: (PdfPageFormat format) => pdf);
```

**Expected behavior**
Works fine on Mac and Windows.

**Desktop (please complete the following information):**
 - [x] Linux

**Comment by DavBfr** [comment]
Yes, I've seen that. But if you run the app from the command line, it works fine. From vs-code it crashes ...

**Comment by ttulka** [comment]
@DavBfr Unfortunately, it crashes from the command line, too.

Both the dev mode `flutter run -d linux` and from the distribution binary `flutter build linux --release; ./build/linux/release/bundle/myapp`.

Any ideas on how to fix that? Likely is a system lib missing, but which one? More, it crashes on different machines in the same way...

Thanks!

**Comment by DavBfr** [comment]
I don't know, without a backtrace I can't help.

**Comment by ttulka** [comment]
@DavBfr I don't think, I am doing anything special here, just trying to print a doc under Linux.

As I said, I had tried two different Linux machines with the same result. This is suspicious. Is `printing` supposed to work under Linux? Is it tested in a way?

Check out this demo project https://github.com/ttulka/flutter-samples/tree/main/printinglinux
Is it working for you? Under what distribution? (I have Kubuntu & Lubuntu 20.04)

Thanks!

**Comment by DavBfr** [comment]
Fixed in the master branch (printing-5.6.8)

**Comment by ttulka** [comment]
Great, thanks! Will try it out as soon as released.

**Comment by DavBfr** [comment]
Can you try before the release to confirm it's fixed?

In your `pubspec.yaml` file, add:

```yaml
dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
    path: printing
```

**Comment by ttulka** [comment]
I had to use the master version of `pdf` as well as `3.6.6` is needed:
```
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: printing
```

It works again! Tested on Kubuntu 20.04 and on Mac Big Sur 11.5.2 as well.

Thank you!
