### ISSUE TITLE
Saved document doesn't render the number "6" (font works fine in all other applications)

### ISSUE THREAD

**Issue by Lootwig** [DavBfr/dart_pdf#882]
When using the font [News Cycle from Google Fonts](https://fonts.google.com/specimen/News+Cycle?width=3), the following code produces a document with a gap between 5 and 7, at least when viewing it in Chrome or Edge:

```dart
void main() async {
  final font = Font.ttf(
    File('assets/NewsCycle-Regular.ttf').readAsBytesSync().buffer.asByteData(),
  );
  final pdf = Document()
    ..addPage(
      MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: EdgeInsets.zero,
        build: (Context context) {
          return [
            Text('0 1 2 3 4 5 6 7 8 9', style: TextStyle(font: font)),
          ];
        },
      ),
    ); // Page

  File('output.pdf').writeAsBytesSync(await pdf.save());
}
```

**Comment by DavBfr** [comment]
Incredible! the "6" is actually defined as a "9" scaled by -1 on both axes!

**Comment by Lootwig** [comment]
I'm sorry if I'm too uninvolved in typography to grasp the implications, is that something super rare / hard to deal with when reading font files?

**Comment by DavBfr** [comment]
It's already fixed in the master branch.

You can try adding this to your `pubspec.yaml`:

```yaml
dependency_overrides:
  pdf:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: pdf
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf.git
      ref: master
      path: printing
```
