### ISSUE TITLE
Printing.convertHtml not fount on latest version ^2.0.4

### ISSUE THREAD

**Issue by duynp117** [DavBfr/dart_pdf#94]
Hi,

I'm using Printing.convertHtml on version 2.0.4. But the method `convertHtml` is not defined for the class Printing. Please review again.

Thank you very much!

**Comment by DavBfr** [comment]
This version is not yet published, but you can try it using this in your pubspec.yaml:
```yaml
dependency_overrides:
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf
      path: printing
```
And you can tell me how it works for you. If all OK, I can publish this version.
